### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by kacgrzes** [szymongrotha/przesuwanepl#1]
OGÓLNE
- [x] nie zaprosiłeś mnie do kolaboracji

UX
- [x] brakuje ostatniego obrazka (u mnie na kompie go nie widać)
- [x] tylko na pierwszym obrazku po najechaniu pojawiają się ikonki
- [x] spory odstęp między 'kim jesteśmy' a tym obrazkiem w kółku
- [x] brak `<footer>`

KOD HTML
- [x] przenieś wszystkie tagi `<script>` na sam koniec strony (przed znacznik `</body>`)
- [x] na obrazkach brakuje atrybutu `alt`
- [x] pobierz obrazki i umieść je w repozytorium w katalogu img. Dzięki temu nie będzie sytuacji w której w projekcie znikają obrazki
- [x] 101 oraz 102 linijka jest do wyrzucenia

KOD CSS
- [x] używasz jedynie jednego pliku css w `index.html`. Reszta jest do usunięcia
- [x] usuń zakomentowany kod (nie wolno trzymać w repo zakomentowanego kodu)
- [x] popraw wcięcia w CSS'ach

**Comment by kacgrzes** [comment]
- [x] w sekcji "drzwi otwierane" dwa obrazki po najechaniu dziwnie nakładają się na inne obrazki
- [x] na wszystkich obrazkach dalej brakuje alt

**Comment by szymongrotha** [comment]
Hej nie wiem czy ja tego nie widzę (a jest taka możliwość :D) ale wydaje mi się że wszystkie obrazki mają alt="Picture" :) W repo "fix"
